import { ExerciseCatalogSchema, ExerciseSchema } from './schema';
import type { Exercise, MovementPatternId } from './schema';

type RequiredSeed = Pick<
  Exercise,
  | 'id'
  | 'name'
  | 'primaryMuscles'
  | 'secondaryMuscles'
  | 'movementPattern'
  | 'trainingRole'
  | 'equipment'
  | 'locations'
  | 'progressionFamily'
  | 'mediaId'
>;

type ExerciseSeed = RequiredSeed &
  Partial<
    Omit<Exercise, keyof RequiredSeed | 'instructions' | 'commonMistakes'>
  >;

const patternInstructions: Record<MovementPatternId, [string, string, string]> =
  {
    'horizontal-press': [
      'Set the shoulder blades gently down and back before the first repetition.',
      'Lower with control until the upper arm reaches a comfortable depth.',
      'Press away while keeping the wrist stacked over the elbow.',
    ],
    'incline-press': [
      'Set a modest incline and keep the shoulder blades supported by the bench.',
      'Lower toward the upper chest without letting the elbows flare sharply.',
      'Press upward and slightly inward while keeping the ribs controlled.',
    ],
    'vertical-press': [
      'Brace the trunk and begin with the forearms close to vertical.',
      'Press overhead through a comfortable shoulder path without leaning back.',
      'Finish with control, then lower until the elbows reach a comfortable depth.',
    ],
    'horizontal-pull': [
      'Start long through the arm while keeping the torso braced.',
      'Drive the elbow back and draw the shoulder blade toward the spine.',
      'Pause briefly, then return without shrugging or twisting.',
    ],
    'vertical-pull': [
      'Begin with a secure grip and ribs stacked over the pelvis.',
      'Pull the elbows toward the ribs while keeping the neck relaxed.',
      'Return to a controlled overhead stretch without losing shoulder position.',
    ],
    squat: [
      'Set a stable stance and brace before descending.',
      'Sit between the hips and knees while keeping the whole foot grounded.',
      'Drive through the floor and finish tall without overextending the back.',
    ],
    lunge: [
      'Establish a long, stable split stance before loading the movement.',
      'Lower with the front knee tracking in line with the toes.',
      'Push through the front foot while keeping the pelvis level.',
    ],
    hinge: [
      'Soften the knees, brace, and send the hips backward.',
      'Keep the load close while lowering only as far as the spine stays neutral.',
      'Drive the hips forward by squeezing the glutes without leaning back.',
    ],
    'knee-flexion': [
      'Align the machine or band so the knee moves freely through its natural path.',
      'Curl smoothly and pause at the strongest controlled contraction.',
      'Return slowly without letting the hips lift or the stack slam.',
    ],
    'knee-extension': [
      'Align the machine pivot with the knee and set a comfortable range.',
      'Extend the knees smoothly without kicking or lifting the hips.',
      'Pause briefly, then lower the stack under control.',
    ],
    'hip-extension': [
      'Brace the trunk and set the working hip in a stable position.',
      'Drive through the foot and extend the hip without arching the back.',
      'Pause at full hip extension, then return under control.',
    ],
    'plantar-flexion': [
      'Set the forefoot securely and begin from a comfortable heel stretch.',
      'Rise through the ball of the foot without rolling the ankle.',
      'Pause high, then lower the heel slowly through the available range.',
    ],
    'elbow-flexion': [
      'Set the shoulders quietly and begin with the elbows under control.',
      'Curl without swinging the torso or drifting the elbow forward.',
      'Squeeze briefly, then lower through the full comfortable range.',
    ],
    'elbow-extension': [
      'Set the upper arm in a stable position before extending the elbow.',
      'Reach full comfortable extension without snapping the joint.',
      'Return under control while keeping tension on the triceps.',
    ],
    'shoulder-abduction': [
      'Stand tall with the shoulder blades resting naturally.',
      'Raise the arms in a comfortable plane with a soft elbow.',
      'Stop before shrugging, then lower slowly to maintain tension.',
    ],
    'scapular-retraction': [
      'Set the cable or band near face height and brace the torso.',
      'Pull toward the face while spreading the hands and rotating outward.',
      'Pause with the shoulder blades controlled, then return slowly.',
    ],
    'anti-extension': [
      'Brace the abdominals and align the ribs over the pelvis.',
      'Hold the body position without allowing the lower back to sag.',
      'Breathe behind the brace and stop when alignment can no longer be held.',
    ],
    'anti-rotation': [
      'Stand or kneel square to the anchor with a stable base.',
      'Press the hands away while resisting rotation toward the anchor.',
      'Pause with steady breathing, then return without losing trunk position.',
    ],
    'trunk-flexion': [
      'Set the pelvis and ribs in a comfortable stacked position.',
      'Curl the torso by shortening the abdominals without pulling the neck.',
      'Return slowly until the abdominal wall reaches a controlled stretch.',
    ],
    'lateral-flexion': [
      'Stack the shoulders, ribs, and pelvis before loading the side body.',
      'Maintain a long neutral trunk without rotating forward or backward.',
      'Breathe steadily and stop when alignment can no longer be held.',
    ],
    'loaded-carry': [
      'Stand tall with the load controlled and the ribs stacked over the pelvis.',
      'Walk with short steady steps while resisting lean and rotation.',
      'Set the load down safely before posture or grip deteriorates.',
    ],
  };

const patternTags: Record<
  MovementPatternId,
  Exercise['superset']['tags'][number]
> = {
  'horizontal-press': 'push',
  'incline-press': 'push',
  'vertical-press': 'push',
  'horizontal-pull': 'pull',
  'vertical-pull': 'pull',
  squat: 'lower',
  lunge: 'lower',
  hinge: 'lower',
  'knee-flexion': 'lower',
  'knee-extension': 'lower',
  'hip-extension': 'lower',
  'plantar-flexion': 'lower',
  'elbow-flexion': 'arms',
  'elbow-extension': 'arms',
  'shoulder-abduction': 'push',
  'scapular-retraction': 'pull',
  'anti-extension': 'core',
  'anti-rotation': 'core',
  'trunk-flexion': 'core',
  'lateral-flexion': 'core',
  'loaded-carry': 'core',
};

function defineExercise(seed: ExerciseSeed): Exercise {
  const mechanics = seed.mechanics ?? 'compound';
  return ExerciseSchema.parse({
    aliases: [],
    strengthSuitability: 3,
    hypertrophySuitability: 4,
    setupTimeSeconds: 45,
    transitionCost: 2,
    typicalRepRange: { min: 8, max: 12 },
    dropSet: {
      support: mechanics === 'isolation' ? 'safe' : 'conditional',
      reason:
        mechanics === 'isolation'
          ? 'Stable isolation setup supports controlled load reductions.'
          : 'Use only when fatigue will not compromise later priority work.',
    },
    superset: {
      tags: [patternTags[seed.movementPattern], 'low-setup'],
      avoidWithPatterns: [],
    },
    laterality: 'bilateral',
    mechanics,
    stabilityDemand: 3,
    gripDemand: 2,
    jointStress: [],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: [],
    instructions: patternInstructions[seed.movementPattern],
    commonMistakes: [
      'Using momentum instead of controlling the intended range of motion.',
      'Continuing after position or joint comfort begins to deteriorate.',
    ],
    difficulty: 'intermediate',
    warmup: {
      rampEligible: mechanics === 'compound',
      minimumRampSets: mechanics === 'compound' ? 2 : 0,
      protocol: mechanics === 'compound' ? 'load-ramp' : 'none',
    },
    plateMath: {
      loadType: 'bodyweight',
      barWeightCompatible: false,
      eachHand: false,
    },
    ...seed,
    productionEnabled: true,
  });
}

export const exerciseCatalog = ExerciseCatalogSchema.parse([
  defineExercise({
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    aliases: ['bench press'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    movementPattern: 'horizontal-press',
    trainingRole: 'primary-strength',
    strengthSuitability: 5,
    equipment: {
      required: ['barbell', 'weight-plates', 'adjustable-bench'],
      optional: ['squat-rack'],
    },
    locations: ['home', 'gym'],
    setupTimeSeconds: 120,
    transitionCost: 4,
    typicalRepRange: { min: 3, max: 8 },
    dropSet: {
      support: 'avoid',
      reason:
        'Unassisted barbell load changes are too slow and fatigue-sensitive.',
    },
    jointStress: ['shoulder-extension', 'wrist-extension'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: [
      'dumbbell-bench-press',
      'machine-chest-press',
      'push-up',
    ],
    mediaId: 'press-placeholder',
    progressionFamily: 'horizontal-press',
    plateMath: {
      loadType: 'barbell-total',
      barWeightCompatible: true,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    movementPattern: 'horizontal-press',
    trainingRole: 'primary-hypertrophy',
    strengthSuitability: 4,
    hypertrophySuitability: 5,
    equipment: { required: ['dumbbells', 'adjustable-bench'], optional: [] },
    locations: ['home', 'gym'],
    setupTimeSeconds: 75,
    jointStress: ['shoulder-extension'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: [
      'barbell-bench-press',
      'machine-chest-press',
      'push-up',
    ],
    mediaId: 'press-placeholder',
    progressionFamily: 'horizontal-press',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primaryMuscles: ['upper-chest', 'chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    movementPattern: 'incline-press',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['dumbbells', 'adjustable-bench'], optional: [] },
    locations: ['home', 'gym'],
    setupTimeSeconds: 90,
    jointStress: ['shoulder-extension'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['dumbbell-bench-press', 'push-up'],
    mediaId: 'press-placeholder',
    progressionFamily: 'incline-press',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'push-up',
    name: 'Push-Up',
    aliases: ['press-up'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts', 'abs'],
    movementPattern: 'horizontal-press',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['bodyweight'], optional: ['resistance-band'] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 10,
    transitionCost: 1,
    typicalRepRange: { min: 8, max: 30 },
    dropSet: {
      support: 'safe',
      reason: 'Leverage can be adjusted without handling external load.',
    },
    difficulty: 'beginner',
    commonSubstitutions: ['dumbbell-bench-press', 'close-grip-push-up'],
    mediaId: 'press-placeholder',
    progressionFamily: 'horizontal-press',
  }),
  defineExercise({
    id: 'cable-fly',
    name: 'Cable Fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front-delts'],
    movementPattern: 'horizontal-press',
    trainingRole: 'isolation',
    equipment: { required: ['cable-station'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 70,
    mechanics: 'isolation',
    stabilityDemand: 2,
    jointStress: ['shoulder-extension'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['machine-chest-press', 'push-up'],
    mediaId: 'press-placeholder',
    progressionFamily: 'horizontal-press',
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    movementPattern: 'horizontal-press',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['chest-press-machine'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 55,
    stabilityDemand: 1,
    dropSet: {
      support: 'safe',
      reason: 'The selectorized stack supports quick, controlled reductions.',
    },
    commonSubstitutions: ['dumbbell-bench-press', 'push-up'],
    mediaId: 'press-placeholder',
    progressionFamily: 'horizontal-press',
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'pull-up',
    name: 'Pull-Up',
    aliases: ['chin over bar pull-up'],
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper-back', 'forearms'],
    movementPattern: 'vertical-pull',
    trainingRole: 'primary-strength',
    strengthSuitability: 5,
    equipment: { required: ['pull-up-bar'], optional: ['resistance-band'] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 25,
    gripDemand: 5,
    stabilityDemand: 4,
    typicalRepRange: { min: 4, max: 12 },
    dropSet: {
      support: 'conditional',
      reason: 'A band-assisted reduction is safe only with a stable setup.',
    },
    jointStress: ['elbow-flexor-tendon', 'shoulder-overhead'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['lat-pulldown', 'one-arm-dumbbell-row'],
    mediaId: 'pull-placeholder',
    progressionFamily: 'vertical-pull',
  }),
  defineExercise({
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper-back', 'forearms'],
    movementPattern: 'vertical-pull',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['lat-pulldown'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 50,
    gripDemand: 4,
    jointStress: ['elbow-flexor-tendon', 'shoulder-overhead'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['pull-up', 'seated-cable-row'],
    mediaId: 'pull-placeholder',
    progressionFamily: 'vertical-pull',
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'one-arm-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    primaryMuscles: ['lats', 'upper-back'],
    secondaryMuscles: ['biceps', 'rear-delts', 'forearms'],
    movementPattern: 'horizontal-pull',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['dumbbells'], optional: ['adjustable-bench'] },
    locations: ['home', 'gym'],
    laterality: 'unilateral',
    gripDemand: 4,
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'caution',
    },
    jointStress: ['lumbar-loading'],
    commonSubstitutions: ['seated-cable-row', 'pull-up'],
    mediaId: 'pull-placeholder',
    progressionFamily: 'horizontal-pull',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    primaryMuscles: ['upper-back', 'lats'],
    secondaryMuscles: ['biceps', 'rear-delts', 'forearms'],
    movementPattern: 'horizontal-pull',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['seated-row'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 45,
    gripDemand: 3,
    commonSubstitutions: ['one-arm-dumbbell-row', 'lat-pulldown'],
    mediaId: 'pull-placeholder',
    progressionFamily: 'horizontal-pull',
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'goblet-squat',
    name: 'Goblet Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    movementPattern: 'squat',
    trainingRole: 'secondary-strength',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 20,
    jointStress: ['knee-deep-flexion', 'hip-deep-flexion'],
    considerations: {
      shoulder: 'neutral',
      knee: 'caution',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['leg-press', 'bulgarian-split-squat'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'squat',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'spinal-erectors', 'abs'],
    movementPattern: 'squat',
    trainingRole: 'primary-strength',
    strengthSuitability: 5,
    equipment: {
      required: ['barbell', 'weight-plates', 'squat-rack'],
      optional: [],
    },
    locations: ['home', 'gym'],
    setupTimeSeconds: 150,
    transitionCost: 5,
    typicalRepRange: { min: 3, max: 8 },
    dropSet: {
      support: 'avoid',
      reason: 'Rack changes under fatigue are not a safe time-saving tool.',
    },
    stabilityDemand: 5,
    jointStress: ['knee-deep-flexion', 'lumbar-loading', 'hip-deep-flexion'],
    considerations: {
      shoulder: 'caution',
      knee: 'caution',
      lowerBack: 'caution',
    },
    commonSubstitutions: ['goblet-squat', 'leg-press'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'squat',
    plateMath: {
      loadType: 'barbell-total',
      barWeightCompatible: true,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'leg-press',
    name: 'Leg Press',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'squat',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['leg-press'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 60,
    stabilityDemand: 1,
    jointStress: ['knee-deep-flexion', 'hip-deep-flexion'],
    considerations: {
      shoulder: 'neutral',
      knee: 'caution',
      lowerBack: 'caution',
    },
    commonSubstitutions: ['goblet-squat', 'bulgarian-split-squat'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'squat',
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    movementPattern: 'lunge',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['dumbbells', 'adjustable-bench'], optional: [] },
    locations: ['home', 'gym'],
    setupTimeSeconds: 55,
    laterality: 'unilateral',
    stabilityDemand: 4,
    jointStress: ['knee-deep-flexion'],
    considerations: {
      shoulder: 'neutral',
      knee: 'caution',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['goblet-squat', 'leg-press'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'single-leg-squat',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    aliases: ['RDL'],
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['spinal-erectors', 'forearms'],
    movementPattern: 'hinge',
    trainingRole: 'primary-strength',
    strengthSuitability: 5,
    equipment: {
      required: ['barbell', 'weight-plates'],
      optional: ['squat-rack'],
    },
    locations: ['home', 'gym'],
    setupTimeSeconds: 105,
    transitionCost: 4,
    typicalRepRange: { min: 5, max: 10 },
    dropSet: {
      support: 'avoid',
      reason: 'Grip and spinal fatigue make rapid reductions a poor fit.',
    },
    gripDemand: 5,
    stabilityDemand: 5,
    jointStress: ['lumbar-loading'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'caution',
    },
    commonSubstitutions: ['dumbbell-romanian-deadlift', 'lying-leg-curl'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'hip-hinge',
    plateMath: {
      loadType: 'barbell-total',
      barWeightCompatible: true,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['spinal-erectors', 'forearms'],
    movementPattern: 'hinge',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 25,
    gripDemand: 4,
    jointStress: ['lumbar-loading'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'caution',
    },
    commonSubstitutions: ['romanian-deadlift', 'lying-leg-curl'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'hip-hinge',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    movementPattern: 'knee-flexion',
    trainingRole: 'isolation',
    equipment: { required: ['leg-curl'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 40,
    mechanics: 'isolation',
    stabilityDemand: 1,
    commonSubstitutions: ['dumbbell-romanian-deadlift'],
    mediaId: 'lower-placeholder',
    progressionFamily: 'knee-flexion',
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primaryMuscles: ['front-delts'],
    secondaryMuscles: ['triceps', 'side-delts'],
    movementPattern: 'vertical-press',
    trainingRole: 'secondary-strength',
    equipment: { required: ['dumbbells'], optional: ['adjustable-bench'] },
    locations: ['home', 'gym'],
    setupTimeSeconds: 60,
    jointStress: ['shoulder-overhead'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'caution',
    },
    commonSubstitutions: ['cable-lateral-raise', 'push-up'],
    mediaId: 'press-placeholder',
    progressionFamily: 'vertical-press',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscles: ['side-delts'],
    secondaryMuscles: ['front-delts'],
    movementPattern: 'shoulder-abduction',
    trainingRole: 'specialization',
    equipment: { required: ['cable-station'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 45,
    mechanics: 'isolation',
    laterality: 'unilateral',
    stabilityDemand: 2,
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['dumbbell-shoulder-press'],
    mediaId: 'arms-placeholder',
    progressionFamily: 'lateral-raise',
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'face-pull',
    name: 'Cable Face Pull',
    primaryMuscles: ['rear-delts', 'upper-back'],
    secondaryMuscles: ['traps'],
    movementPattern: 'scapular-retraction',
    trainingRole: 'corrective',
    equipment: { required: ['cable-station'], optional: ['resistance-band'] },
    locations: ['gym'],
    setupTimeSeconds: 35,
    mechanics: 'isolation',
    stabilityDemand: 2,
    commonSubstitutions: ['seated-cable-row'],
    mediaId: 'pull-placeholder',
    progressionFamily: 'rear-delt',
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['brachialis', 'forearms'],
    movementPattern: 'elbow-flexion',
    trainingRole: 'specialization',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 15,
    transitionCost: 1,
    mechanics: 'isolation',
    laterality: 'alternating',
    gripDemand: 3,
    jointStress: ['elbow-flexor-tendon'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['hammer-curl', 'cable-curl'],
    mediaId: 'arms-placeholder',
    progressionFamily: 'elbow-flexion-supinated',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'hammer-curl',
    name: 'Hammer Curl',
    primaryMuscles: ['brachialis', 'biceps'],
    secondaryMuscles: ['forearms'],
    movementPattern: 'elbow-flexion',
    trainingRole: 'specialization',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 15,
    transitionCost: 1,
    mechanics: 'isolation',
    laterality: 'alternating',
    gripDemand: 3,
    jointStress: ['elbow-flexor-tendon'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['dumbbell-curl', 'cable-curl'],
    mediaId: 'arms-placeholder',
    progressionFamily: 'elbow-flexion-neutral',
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'cable-curl',
    name: 'Cable Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['brachialis', 'forearms'],
    movementPattern: 'elbow-flexion',
    trainingRole: 'specialization',
    equipment: { required: ['cable-station'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 30,
    mechanics: 'isolation',
    gripDemand: 2,
    jointStress: ['elbow-flexor-tendon'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['dumbbell-curl', 'hammer-curl'],
    mediaId: 'arms-placeholder',
    progressionFamily: 'elbow-flexion-supinated',
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'cable-triceps-pressdown',
    name: 'Cable Triceps Pressdown',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow-extension',
    trainingRole: 'specialization',
    equipment: { required: ['cable-station'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 25,
    mechanics: 'isolation',
    jointStress: ['elbow-extension-tendon'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: [
      'overhead-cable-triceps-extension',
      'close-grip-push-up',
    ],
    mediaId: 'arms-placeholder',
    progressionFamily: 'elbow-extension',
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'overhead-cable-triceps-extension',
    name: 'Overhead Cable Triceps Extension',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow-extension',
    trainingRole: 'specialization',
    equipment: { required: ['cable-station'], optional: [] },
    locations: ['gym'],
    setupTimeSeconds: 40,
    mechanics: 'isolation',
    jointStress: ['shoulder-overhead', 'elbow-extension-tendon'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['cable-triceps-pressdown', 'close-grip-push-up'],
    mediaId: 'arms-placeholder',
    progressionFamily: 'elbow-extension',
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'close-grip-push-up',
    name: 'Close-Grip Push-Up',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front-delts', 'abs'],
    movementPattern: 'elbow-extension',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['bodyweight'], optional: ['resistance-band'] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 10,
    transitionCost: 1,
    typicalRepRange: { min: 8, max: 25 },
    dropSet: {
      support: 'safe',
      reason:
        'Hand position or leverage can be adjusted without external load.',
    },
    jointStress: ['wrist-extension', 'elbow-extension-tendon'],
    considerations: {
      shoulder: 'neutral',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['cable-triceps-pressdown', 'push-up'],
    mediaId: 'arms-placeholder',
    progressionFamily: 'elbow-extension',
  }),
  defineExercise({
    id: 'plank',
    name: 'Forearm Plank',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'glutes'],
    movementPattern: 'anti-extension',
    trainingRole: 'corrective',
    equipment: { required: ['bodyweight'], optional: ['exercise-mat'] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 10,
    transitionCost: 1,
    typicalRepRange: { min: 20, max: 60 },
    mechanics: 'isolation',
    difficulty: 'beginner',
    warmup: { rampEligible: false, minimumRampSets: 0, protocol: 'none' },
    commonSubstitutions: ['band-pallof-press'],
    mediaId: 'core-placeholder',
    progressionFamily: 'anti-extension',
  }),
  defineExercise({
    id: 'band-pallof-press',
    name: 'Band Pallof Press',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: ['glutes'],
    movementPattern: 'anti-rotation',
    trainingRole: 'corrective',
    equipment: { required: ['resistance-band'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    setupTimeSeconds: 20,
    transitionCost: 1,
    typicalRepRange: { min: 8, max: 15 },
    mechanics: 'isolation',
    laterality: 'unilateral',
    difficulty: 'beginner',
    warmup: { rampEligible: false, minimumRampSets: 0, protocol: 'none' },
    commonSubstitutions: ['plank'],
    mediaId: 'core-placeholder',
    progressionFamily: 'anti-rotation',
    plateMath: {
      loadType: 'band',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'incline-push-up',
    name: 'Incline Push-Up',
    aliases: ['elevated push-up'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts', 'abs'],
    movementPattern: 'horizontal-press',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['bodyweight', 'adjustable-bench'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'horizontal-press',
    mediaId: 'press-placeholder',
    difficulty: 'beginner',
    setupTimeSeconds: 10,
    commonSubstitutions: ['push-up', 'machine-chest-press'],
  }),
  defineExercise({
    id: 'parallel-bar-dip',
    name: 'Parallel-Bar Dip',
    aliases: ['chest dip', 'triceps dip'],
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front-delts'],
    movementPattern: 'horizontal-press',
    trainingRole: 'secondary-strength',
    equipment: { required: ['bodyweight', 'dip-station'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'horizontal-press',
    mediaId: 'press-placeholder',
    typicalRepRange: { min: 5, max: 15 },
    jointStress: ['shoulder-extension', 'elbow-extension-tendon'],
    considerations: {
      shoulder: 'caution',
      knee: 'neutral',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['close-grip-push-up', 'machine-chest-press'],
  }),
  defineExercise({
    id: 'pec-deck-fly',
    name: 'Pec Deck Fly',
    aliases: ['machine chest fly'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front-delts'],
    movementPattern: 'horizontal-press',
    trainingRole: 'isolation',
    equipment: { required: ['pec-deck'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'horizontal-press',
    mediaId: 'press-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['cable-fly', 'machine-chest-press'],
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primaryMuscles: ['front-delts'],
    secondaryMuscles: ['triceps', 'side-delts'],
    movementPattern: 'vertical-press',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['shoulder-press-machine'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'vertical-press',
    mediaId: 'press-placeholder',
    commonSubstitutions: ['dumbbell-shoulder-press'],
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscles: ['side-delts'],
    secondaryMuscles: ['traps'],
    movementPattern: 'shoulder-abduction',
    trainingRole: 'specialization',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    progressionFamily: 'lateral-raise',
    mediaId: 'press-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['cable-lateral-raise'],
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    aliases: ['machine reverse fly'],
    primaryMuscles: ['rear-delts', 'upper-back'],
    secondaryMuscles: ['traps'],
    movementPattern: 'scapular-retraction',
    trainingRole: 'isolation',
    equipment: { required: ['pec-deck'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'rear-delt',
    mediaId: 'pull-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['face-pull', 'seated-cable-row'],
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'assisted-pull-up',
    name: 'Assisted Pull-Up',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper-back', 'forearms'],
    movementPattern: 'vertical-pull',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['assisted-pullup-dip'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'vertical-pull',
    mediaId: 'pull-placeholder',
    difficulty: 'beginner',
    commonSubstitutions: ['pull-up', 'lat-pulldown'],
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'chest-supported-dumbbell-row',
    name: 'Chest-Supported Dumbbell Row',
    primaryMuscles: ['upper-back', 'lats'],
    secondaryMuscles: ['biceps', 'rear-delts'],
    movementPattern: 'horizontal-pull',
    trainingRole: 'primary-hypertrophy',
    equipment: { required: ['dumbbells', 'adjustable-bench'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'horizontal-pull',
    mediaId: 'pull-placeholder',
    commonSubstitutions: ['one-arm-dumbbell-row', 'seated-cable-row'],
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'inverted-row',
    name: 'Inverted Row',
    aliases: ['body row'],
    primaryMuscles: ['upper-back', 'lats'],
    secondaryMuscles: ['biceps', 'rear-delts', 'abs'],
    movementPattern: 'horizontal-pull',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['bodyweight', 'squat-rack'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'horizontal-pull',
    mediaId: 'pull-placeholder',
    commonSubstitutions: ['one-arm-dumbbell-row', 'seated-cable-row'],
  }),
  defineExercise({
    id: 'straight-arm-pulldown',
    name: 'Straight-Arm Cable Pulldown',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps', 'abs'],
    movementPattern: 'vertical-pull',
    trainingRole: 'isolation',
    equipment: { required: ['cable-station'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'vertical-pull',
    mediaId: 'pull-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['lat-pulldown', 'pull-up'],
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'barbell-front-squat',
    name: 'Barbell Front Squat',
    aliases: ['front squat'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'spinal-erectors'],
    movementPattern: 'squat',
    trainingRole: 'primary-strength',
    equipment: {
      required: ['barbell', 'weight-plates', 'squat-rack'],
      optional: [],
    },
    locations: ['home', 'gym'],
    progressionFamily: 'squat',
    mediaId: 'lower-placeholder',
    jointStress: ['knee-deep-flexion', 'lumbar-loading'],
    considerations: {
      shoulder: 'caution',
      knee: 'caution',
      lowerBack: 'caution',
    },
    commonSubstitutions: ['goblet-squat', 'leg-press'],
    plateMath: {
      loadType: 'barbell-total',
      barWeightCompatible: true,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'dumbbell-step-up',
    name: 'Dumbbell Step-Up',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    movementPattern: 'lunge',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['dumbbells', 'adjustable-bench'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'single-leg-squat',
    mediaId: 'lower-placeholder',
    laterality: 'unilateral',
    commonSubstitutions: ['bulgarian-split-squat', 'goblet-squat'],
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'walking-lunge',
    name: 'Dumbbell Walking Lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    movementPattern: 'lunge',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'single-leg-squat',
    mediaId: 'lower-placeholder',
    laterality: 'alternating',
    commonSubstitutions: ['bulgarian-split-squat', 'dumbbell-step-up'],
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
  defineExercise({
    id: 'machine-leg-extension',
    name: 'Machine Leg Extension',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    movementPattern: 'knee-extension',
    trainingRole: 'isolation',
    equipment: { required: ['leg-extension'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'knee-extension',
    mediaId: 'lower-placeholder',
    mechanics: 'isolation',
    considerations: {
      shoulder: 'neutral',
      knee: 'caution',
      lowerBack: 'neutral',
    },
    commonSubstitutions: ['leg-press', 'goblet-squat'],
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    movementPattern: 'hip-extension',
    trainingRole: 'primary-hypertrophy',
    equipment: {
      required: ['barbell', 'weight-plates', 'adjustable-bench'],
      optional: [],
    },
    locations: ['home', 'gym'],
    progressionFamily: 'hip-extension',
    mediaId: 'lower-placeholder',
    commonSubstitutions: ['glute-bridge', 'dumbbell-romanian-deadlift'],
    plateMath: {
      loadType: 'barbell-total',
      barWeightCompatible: true,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'glute-bridge',
    name: 'Bodyweight Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    movementPattern: 'hip-extension',
    trainingRole: 'secondary-hypertrophy',
    equipment: { required: ['bodyweight'], optional: ['exercise-mat'] },
    locations: ['home', 'gym', 'travel'],
    progressionFamily: 'hip-extension',
    mediaId: 'lower-placeholder',
    difficulty: 'beginner',
    commonSubstitutions: ['barbell-hip-thrust', 'dumbbell-romanian-deadlift'],
  }),
  defineExercise({
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    movementPattern: 'plantar-flexion',
    trainingRole: 'specialization',
    equipment: { required: ['bodyweight'], optional: ['dumbbells'] },
    locations: ['home', 'gym', 'travel'],
    progressionFamily: 'plantar-flexion',
    mediaId: 'lower-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['machine-seated-calf-raise'],
  }),
  defineExercise({
    id: 'machine-seated-calf-raise',
    name: 'Machine Seated Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    movementPattern: 'plantar-flexion',
    trainingRole: 'specialization',
    equipment: { required: ['calf-raise-machine'], optional: [] },
    locations: ['gym'],
    progressionFamily: 'plantar-flexion',
    mediaId: 'lower-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['standing-calf-raise'],
    plateMath: {
      loadType: 'machine-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    movementPattern: 'trunk-flexion',
    trainingRole: 'isolation',
    equipment: { required: ['bodyweight', 'exercise-mat'], optional: [] },
    locations: ['home', 'gym', 'travel'],
    progressionFamily: 'trunk-flexion',
    mediaId: 'core-placeholder',
    mechanics: 'isolation',
    difficulty: 'beginner',
    commonSubstitutions: ['cable-crunch', 'plank'],
  }),
  defineExercise({
    id: 'cable-crunch',
    name: 'Kneeling Cable Crunch',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    movementPattern: 'trunk-flexion',
    trainingRole: 'specialization',
    equipment: { required: ['cable-station'], optional: ['exercise-mat'] },
    locations: ['gym'],
    progressionFamily: 'trunk-flexion',
    mediaId: 'core-placeholder',
    mechanics: 'isolation',
    commonSubstitutions: ['reverse-crunch', 'plank'],
    plateMath: {
      loadType: 'cable-stack',
      barWeightCompatible: false,
      eachHand: false,
    },
  }),
  defineExercise({
    id: 'side-plank',
    name: 'Side Plank',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'glutes'],
    movementPattern: 'lateral-flexion',
    trainingRole: 'corrective',
    equipment: { required: ['bodyweight'], optional: ['exercise-mat'] },
    locations: ['home', 'gym', 'travel'],
    progressionFamily: 'lateral-flexion',
    mediaId: 'core-placeholder',
    mechanics: 'isolation',
    laterality: 'unilateral',
    commonSubstitutions: ['band-pallof-press', 'plank'],
  }),
  defineExercise({
    id: 'suitcase-carry',
    name: 'Dumbbell Suitcase Carry',
    primaryMuscles: ['obliques', 'forearms'],
    secondaryMuscles: ['traps', 'abs', 'glutes'],
    movementPattern: 'loaded-carry',
    trainingRole: 'corrective',
    equipment: { required: ['dumbbells'], optional: [] },
    locations: ['home', 'gym'],
    progressionFamily: 'loaded-carry',
    mediaId: 'core-placeholder',
    laterality: 'unilateral',
    typicalRepRange: { min: 20, max: 60 },
    commonSubstitutions: ['side-plank', 'band-pallof-press'],
    plateMath: {
      loadType: 'dumbbell-each-hand',
      barWeightCompatible: false,
      eachHand: true,
    },
  }),
]);

export const exerciseById = new Map(
  exerciseCatalog.map((exercise) => [exercise.id, exercise]),
);

export function findExercises(query: string): Exercise[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return exerciseCatalog;
  return exerciseCatalog.filter((exercise) =>
    [exercise.name, exercise.id, ...exercise.aliases]
      .join(' ')
      .toLowerCase()
      .includes(normalized),
  );
}
